### ISSUE TITLE
Compile error.

### ISSUE THREAD

**Issue by arielba** [Hieromon/AutoConnect#173]
Hi people. When i trie to compile a simple sketch (as AutoConnect.ino) it give me an error in a library
The error is this.

AutoConnectUploadImpl.h:154:60: error: expected ':' before ';' token
uint8_t oflag = *mode == 'w' ? FILE_WRITE : FILE_READ;
Could i get some help ?
Thanks a lot.

**Comment by Hieromon** [comment]
No information was provided to reproduce the problem, and it cannot continue the investigation.
The library has built by CI and successfully tested. If the problem is in a specific environment, post to another community, such as the Arduino forum.
Close, it will reopen that present more specific occurrence conditions.
