### ISSUE TITLE
Support for ESP32-S2 modules

### ISSUE THREAD

**Issue by sundar19** [Hieromon/AutoConnect#223]
I am planning to use ESP32-S2-WROOM in my project. Does AutoConnect support this? Just trying to ensure before placing an order.
Thanks!!!

**Comment by Hieromon** [comment]
To be precise, is the ESP32 arduino core support ESP32-S2? synonymously.
I think I'm still working on it.
https://github.com/espressif/arduino-esp32/pull/3990

**Comment by sundar19** [comment]
Yes , oh ok but still I might be able to use this autoconnect with s2 series if iam right? 
Thanks!

**Comment by Hieromon** [comment]
Well, it depends on the implementation of the arduino core for ESP32-S2. Since AutoConnect does not use a process other than loop thread, it will work if backward compatibility will be ensured for the core libraries especially WebServer class.
However, in the current work, the WiFi class has changed for both AP and STA. I won't know without testing how it will affect AutoConnect.

**Comment by sundar19** [comment]
Thank you so much @Hieromon , Good luck for your Esp32-S2 implementation! Hope you notify in your repo after its over !
Thanks!

**Comment by Hieromon** [comment]
@sundar19 Thank you for increasing my homework. :-)
