### ISSUE TITLE
On an ESP8266 when a WiFiClientSecure client is used in a sketch along with AutoConnect library and AC_AUTH_DIGEST or AC_AUTH_BASIC config is used, the autoconnect pages are not accessible

### ISSUE THREAD

**Issue by v-c** [Hieromon/AutoConnect#331]
On an ESP8266 when a WiFiClientSecure client is used in a sketch along with AutoConnect library  the and AC_AUTH_DIGEST or AC_AUTH_BASIC config is used the autoconnect pages are not accessible. 

Here's a simple sketch that demonstrates the problem. If you comment out the #define useSecureMQTT and load the sketch, then the _ac pages are accessible again. Note that this behavior has been reproduced on an ESP8266. 

[reproduction.txt](https://github.com/Hieromon/AutoConnect/files/6175000/reproduction.txt)

**Comment by v-c** [comment]
I tried a similar sketch on the ESP32 and it works fine there. I believe the issue may be the underlying libraries, specifically WiFiClientSecure and its interaction with AutoConnect. I am fine if you want to document the issue and close it if you believe it is not something entirely up to AutoConnect to fix.

**Comment by Hieromon** [comment]
If the encountered phenomenon with **"the autoconnect pages are not accessible"** is **"accessing /_ac results in a blank page response"**, it may not be a problem due to the WiFiClientSecure.
https://hieromon.github.io/AutoConnect/faq.html#some-autoconnect-page-is-cut-off

Please take the debug log with specifying **AC_DEBUG** and **PB_DEBUG**, then check if the following PageBuilder failure has occurred.
```
[PB] Failed building, free heap:<Size of free heap>
```
If you have seen the failure log as above, it's due to a simply insufficient heap.
This issue has resolved in [AutoConnect v1.2.3](https://github.com/Hieromon/AutoConnect/tree/enhance/v123) and [PageBuiler v1.5.0](https://github.com/Hieromon/PageBuilder/tree/enhance/v150). AutoConnect authentication works with the sketch you provided, at least in my environment with AutoConnect v1.2.3 and PageBuilder v1.5.0.
However, those versions have not been released yet.

**Comment by v-c** [comment]
Thanks @Hieromon. I will wait until AutoConnect v1.2.3 and PageBuilder v1.5.0 are released to test and close out this issue if it is no longer reproducible.

**Comment by Hieromon** [comment]
@v-c Ok, If possible, you can pre-validate using RC version staged in each branch.
PageBuilder v1.5.0 has already been tested. The release of AutoConnect v1.2.3 will be skipped. The next valid version is v.1.3.0, and its release will still take some time.
