### ISSUE TITLE
EEPROM

### ISSUE THREAD

**Issue by fruktiz32** [Hieromon/AutoConnect#349]
Does EEPROM example works on ESP32, becaus I can run the program, but variables do not save properly.

**Comment by Hieromon** [comment]
The EEPROM example bundled with the AutoConnect library is for ESP8266.
Also, when using EEPROM with ESP32, you do not have to worry about it because it does not conflict with the area of AutoConnect credentials. Please refer to the EEPROM example of the ESP32 core.

This topic is not related to AutoConnect library issues, closing.
