### ISSUE TITLE
password

### ISSUE THREAD

**Issue by clotaireFrance** [Hieromon/AutoConnect#461]
Hello, 

on esp82666 esp12E,

I don't understand how to connect to AP, on the first time?

what is the password of the wifiap?

**Comment by Hieromon** [comment]
Read through the [AutoConnect documentation](https://hieromon.github.io/AutoConnect/index.html). The basic usage has already been described. Especially the first usage.
Refs: https://hieromon.github.io/AutoConnect/gettingstarted.html#run-at-first
Also, for simple questions the [Discussions](https://github.com/Hieromon/AutoConnect/discussions) is open; the Issue is not a [FAQ](https://hieromon.github.io/AutoConnect/faq.html#4-reports-the-issue-to-autoconnect-github-repository).
