### ISSUE TITLE
Can't click on "choose file" on the OTA update page on Android phones

### ISSUE THREAD

**Issue by cremus** [Hieromon/AutoConnect#494]
Hello,

On some android phones, I am not able to press on the choose file button. **However,** this is **only** in the "pop-up" (I don't know the official name) portal that automatically comes up when the device is chosen in the WiFi settings on the phone. When you use any generic web browser on the phone, the button works just fine. The UI suggests a press by dimming the button slightly for a fraction of a second, but nothing happens.

On all iPhone's the button works fine in browsers and the pop-up page. On my PC running windows 10 it works fine on all browsers as well.

Tested with iPhone XR with latest iOS which works fine.
Does not work with Oneplus Nord V1 with Android 11.1 and Oppo A90.

I think that's its more likely to be an Android type bug, but nevertheless I think its handy to report it here as well.

**Comment by Hieromon** [comment]
This issue has already been described in the Discussions #489.
The cause of the problem is that Android WebView doesn't allow the HTML `input type="file"` element to work. At this time, AutoConnect has no plans to implement a method other than `input type="file"` for OTA file choosing.
However, discussions are underway to enable file selection in Android WebView.
