### ISSUE TITLE
AutoReconnect Fails

### ISSUE THREAD

**Issue by fabltd** [Hieromon/AutoConnect#530]
Auto Reconnect fails if:

Wifi Point is powered off. Device with esp32 is powered up. Wifi Point powered up. AutoReconnect fails to reconnect to WifiPoint if wifi point is slow to boot.

AutReconnect=true is present.

Is there a way to diagnose?

**Comment by Hieromon** [comment]
@fabltd To know if the connection to the access point is failing due to AP startup delays, enable both the Arduino core debugging option and the AutoConnect debugging option.
The [core debug level](https://espressif-docs.readthedocs-hosted.com/projects/arduino-esp32/en/latest/guides/tools_menu.html?highlight=debug#core-debug-level) is specified the verbose in the Arduino IDE. Also enable the [AC_DEBUG](https://hieromon.github.io/AutoConnect/adothers.html#debug-print) macro for AutoConnect debug logging. With those settings, you will be able to see the trace of AutoConnect execution on the serial monitor.

In general, the phenomenon you have encountered may be resolved by specifying the [reconnectInterval](https://hieromon.github.io/AutoConnect/apiconfig.html#reconnectinterval) option along with autoReconnect. See https://hieromon.github.io/AutoConnect/adconnection.html#automatic-reconnect-background

**Comment by Hieromon** [comment]
Closed due to lack of replies over a long period of time. Probably a mistake in usage.
